### ISSUE TITLE
Checking encryption keys failed.     java.security.NoSuchAlgorithmException: KeyFactory RSA implementation not found

### ISSUE THREAD

**Issue by ahmostafa** [mibrito707/cordova-plugin-secure-storage#8]
This error appeared on samsung device 
android version 5.1.1

java.security.NoSuchAlgorithmException: KeyFactory RSA implementation not found
        at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:190)
        at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:183)
        at java.security.KeyFactory.getInstance(KeyFactory.java:136)
        at java.security.KeyFactory.getInstance(KeyFactory.java:110)
        at com.crypho.plugins.b.a(SourceFile:65)
        at com.crypho.plugins.SecureStorage.execute(SourceFile:97)
        at org.apache.cordova.CordovaPlugin.execute(SourceFile:117)
        at org.apache.cordova.CordovaPlugin.execute(SourceFile:98)
        at org.apache.cordova.PluginManager.exec(SourceFile:132)
        at org.apache.cordova.CordovaBridge.jsExec(SourceFile:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SourceFile:41)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 24 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/xx/Library/Android/sdk)
   ios-deploy        : 1.9.4
   NodeJS            : v10.16.3 (/usr/local/Cellar/node@10/10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

**Comment by oddcb** [comment]
Hi. I experienced the same issue on a Samsung SM-T530 tablet with Android 5.0.2.

It seems the problem is that although when the keypair is created a check is done to see if the newer apis are available, the same check is not done when trying to determine if the keys are available. 

I ended up rewriting the code so that it also checks the api level when `encryptionKeysAvailable` is called: 

```
    /**
     * Check if Encryption Keys are available and secure.
     *
     * @param alias
     * @return boolean
     */
    static boolean encryptionKeysAvailable(String alias) {
        return IS_API_23_AVAILABLE ? isEntryAvailable(alias) : isEntryAvailableLegacy(alias);
    }


    @TargetApi(Build.VERSION_CODES.M)
    private static boolean isEntryAvailable(String alias) {
        try {
            Key privateKey = loadKey(Cipher.DECRYPT_MODE, alias);
            if (privateKey == null) {
                return false;
            }
            KeyInfo keyInfo;
            KeyFactory factory = KeyFactory.getInstance(privateKey.getAlgorithm(), KEYSTORE_PROVIDER);
            keyInfo = factory.getKeySpec(privateKey, KeyInfo.class);
            return keyInfo.isInsideSecureHardware();
        } catch (Exception e) {
            Log.i(TAG, "Checking encryption keys failed.", e);
            return false;
        }
    }


    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    private static boolean isEntryAvailableLegacy(String alias) {
        try {
            return loadKey(Cipher.ENCRYPT_MODE, alias) != null;
        } catch (Exception e) {
            return false;
        }
    }
```

One though that stuck out, is that `keyInfo.isInsideSecureHardware();` might return false. You might consider returning true unless you're confident it won't break for any of the devices your users have. For newer devices I guess it will always return true.

**Comment by oddcb** [comment]
I've added a PR now @ahmostafa - see #9
